# Generated by Django 4.1.1 on 2022-10-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
