# Generated by Django 4.1.1 on 2022-10-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_dietplan_dietsupplement_illness_physicalactivities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
    ]
