# Generated by Django 4.1.1 on 2022-10-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bmi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BMI',
        ),
    ]
