# Generated by Django 4.1.1 on 2022-10-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='aa@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='yes', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietsupplement',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='illness',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='illness',
            name='image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='illness',
            name='treatment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='physicalactivities',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
