# Generated by Django 4.1.1 on 2022-10-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_email_remove_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illness',
            old_name='image',
            new_name='img',
        ),
    ]
