# Generated by Django 4.1.1 on 2022-10-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='classification',
            field=models.CharField(choices=[('underweight', 'UNDERWEIGHT'), ('overweight', 'OVERWEIGHT'), ('obese', 'OBESE'), ('normal', 'NORMAL')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='physicalactivities',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
