# Generated by Django 4.1.1 on 2022-10-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_profile_img_dietplan_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dietsupplement',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='illness',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='physicalactivities',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
