# Generated by Django 4.1.1 on 2022-10-25 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_dietschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietschedule',
            name='sunday',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.dietplan'),
        ),
    ]
