# Generated by Django 4.1.1 on 2022-10-25 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_dietschedule_sunday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietschedule',
            name='friday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friday', to='users.dietplan'),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='monday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday', to='users.dietplan'),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='saturday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saturday', to='users.dietplan'),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='sunday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunday', to='users.dietplan'),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='thursday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thursday', to='users.dietplan'),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='tuesday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuesday', to='users.dietplan'),
        ),
        migrations.AlterField(
            model_name='dietschedule',
            name='wednesday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wednesday', to='users.dietplan'),
        ),
    ]
