# Generated by Django 4.1.1 on 2022-10-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_dietschedule_friday_alter_dietschedule_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalactivities',
            name='classification',
            field=models.CharField(choices=[('underweight', 'UNDERWEIGHT'), ('overweight', 'OVERWEIGHT'), ('obese', 'OBESE'), ('normal', 'NORMAL')], default='normal', max_length=50),
        ),
    ]
