# Generated by Django 4.1.1 on 2022-10-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_physicalactivities_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalactivities',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
