# Generated by Django 4.1.2 on 2022-11-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_dietplan_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='classification',
            field=models.CharField(choices=[('Underweight', 'UNDERWEIGHT'), ('Overweight', 'OVERWEIGHT'), ('Obese', 'OBESE'), ('Normal', 'NORMAL'), ('Extremely Obese', 'EXTREMELY OBESE')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='dietsupplement',
            name='classification',
            field=models.CharField(choices=[('Underweight', 'UNDERWEIGHT'), ('Overweight', 'OVERWEIGHT'), ('Obese', 'OBESE'), ('Normal', 'NORMAL'), ('Extremely Obese', 'EXTREMELY OBESE')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='physicalactivities',
            name='classification',
            field=models.CharField(choices=[('Underweight', 'UNDERWEIGHT'), ('Overweight', 'OVERWEIGHT'), ('Obese', 'OBESE'), ('Normal', 'NORMAL'), ('Extremely Obese', 'EXTREMELY OBESE')], default='normal', max_length=50),
        ),
    ]
