# Generated by Django 4.1.1 on 2022-11-28 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_dietplan_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('Underweight', 'UNDERWEIGHT'), ('Normal', 'NORMAL'), ('Overweight', 'OVERWEIGHT'), ('Obese', 'OBESE'), ('Extremely Obese', 'EXTREMELY OBESE')], default='Normal', max_length=50)),
                ('bmi', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
