# Generated by Django 4.1.1 on 2022-11-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userbmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbmi',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
