# Generated by Django 4.1.1 on 2022-11-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_userbmi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbmi',
            name='user',
            field=models.IntegerField(),
        ),
    ]
