# Generated by Django 4.1.1 on 2022-11-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_userbmi_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbmi',
            options={'get_latest_by': ['date'], 'ordering': ['user']},
        ),
    ]
