# Generated by Django 4.1.1 on 2022-11-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_userbmi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbmi',
            options={'get_latest_by': ['date'], 'ordering': ['date']},
        ),
    ]
